/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.oopquiz;

/**
 *
 * @author 66982
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        bt_cal = new javax.swing.JButton();
        tf_CoffeeMachine = new javax.swing.JTextField();
        tf_HelloOOP = new javax.swing.JTextField();
        tf_showpoint = new javax.swing.JTextField();
        lb_hw1 = new javax.swing.JLabel();
        lb_hw2 = new javax.swing.JLabel();
        lb_point = new javax.swing.JLabel();
        tf_hw2 = new javax.swing.JTextField();
        tf_hw1 = new javax.swing.JTextField();
        tf_inheritLab = new javax.swing.JTextField();
        lb_coffee = new javax.swing.JLabel();
        lb_HelloOOP = new javax.swing.JLabel();
        lb_inheritLab = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bt_cal.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        bt_cal.setText("คำนวน");
        bt_cal.setName(""); // NOI18N
        bt_cal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_calMouseClicked(evt);
            }
        });
        bt_cal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_calActionPerformed(evt);
            }
        });

        tf_CoffeeMachine.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        tf_CoffeeMachine.setName(""); // NOI18N

        tf_HelloOOP.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        tf_HelloOOP.setName(""); // NOI18N

        tf_showpoint.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        tf_showpoint.setName(""); // NOI18N

        lb_hw1.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        lb_hw1.setText("กรอกคะเเนนHomework #1");
        lb_hw1.setName(""); // NOI18N

        lb_hw2.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        lb_hw2.setText("กรอกคะเเนนHomework #2");
        lb_hw2.setName(""); // NOI18N

        lb_point.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        lb_point.setText("คะเเนนรวม(หารสอง)");

        tf_hw2.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        tf_hw2.setName(""); // NOI18N

        tf_hw1.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        tf_hw1.setName(""); // NOI18N
        tf_hw1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_hw1ActionPerformed(evt);
            }
        });

        tf_inheritLab.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        tf_inheritLab.setName(""); // NOI18N

        lb_coffee.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        lb_coffee.setText("กรอกคะเเนนCoffeeMachine ");
        lb_coffee.setName(""); // NOI18N

        lb_HelloOOP.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        lb_HelloOOP.setText("กรอกคะเเนนHello OOP");
        lb_HelloOOP.setName("lb_money"); // NOI18N

        lb_inheritLab.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        lb_inheritLab.setText("กรอกคะเเนนOOP Inherit Lab");
        lb_inheritLab.setName("lb_money"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_cal, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(lb_point, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_showpoint, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(163, 163, 163))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lb_HelloOOP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lb_coffee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(6, 6, 6))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lb_inheritLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(6, 6, 6))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lb_hw2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(6, 6, 6)))
                            .addComponent(lb_hw1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tf_HelloOOP, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_CoffeeMachine, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_inheritLab, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_hw2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_hw1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_hw1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_hw1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_hw2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_hw2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_CoffeeMachine, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_coffee, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_inheritLab, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_inheritLab, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb_HelloOOP, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_cal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_showpoint, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_point, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tf_HelloOOP, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_calActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_calActionPerformed
        
    }//GEN-LAST:event_bt_calActionPerformed

    private void bt_calMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_calMouseClicked
        int point = 0;
        Double HW1 = Double.valueOf(tf_hw1.getText());
        Double HW2 = Double.valueOf(tf_hw2.getText());
        Double CoffeeMachine  = Double.valueOf(tf_CoffeeMachine.getText());
        Double InheritLab = Double.valueOf(tf_inheritLab.getText());
        Double HelloOOP = Double.valueOf(tf_HelloOOP.getText());
        point += (HW1 + HW2 + CoffeeMachine + InheritLab + HelloOOP)/ 2 ;
        tf_showpoint.setText(String.valueOf(point));
        
    }//GEN-LAST:event_bt_calMouseClicked

    private void tf_hw1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_hw1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_hw1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cal;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lb_HelloOOP;
    private javax.swing.JLabel lb_coffee;
    private javax.swing.JLabel lb_hw1;
    private javax.swing.JLabel lb_hw2;
    private javax.swing.JLabel lb_inheritLab;
    private javax.swing.JLabel lb_point;
    private javax.swing.JTextField tf_CoffeeMachine;
    private javax.swing.JTextField tf_HelloOOP;
    private javax.swing.JTextField tf_hw1;
    private javax.swing.JTextField tf_hw2;
    private javax.swing.JTextField tf_inheritLab;
    private javax.swing.JTextField tf_showpoint;
    // End of variables declaration//GEN-END:variables
}
